language: node_js
addons:
  chrome: stable
  apt:
    packages:
      - sshpass
cache: yarn
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
node_js:
  - node
script:
  - npm run lint
  - npm run test
  - npm run build:lib
  - npm run build:demo
  - npm run build:dist
  - npm run build:standalone
after_success:
  - npm run coverage
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sshpass -e scp -r -o stricthostkeychecking=no demo/* $DEPLOY_DEST
env:
  global:
    - secure: deRlaZ1x+C3wv9uLdjI9QNLUsIqnB5RRgHQfRn28eMJL+qky0Md98My/H81luGmkaOyTrvZL0Vt6WomsRky577hdBQBDrvMnhqAoyrf+Nhs+ewV4N92szZ7CvAWwjIlceo8cpHCCPjusMWXFOCKX9v53S/CBPSUh0TiXJNsrPzLSJ/e1k1rg7C7xC2eI0aOuhhL+uNIdRMfirLjGLUIor622ZrJjXC95h6d+O0OyJHx21RonYCgF5H0cPp8tULhN1DV2n1Bdwa364o8njrkGJiOVfHeAo6YjKeT0V3WxfMwF/gfxBLVgrSWFfL0bgpbE8wzP6QIxj7Et9+FO62zYTxMIdcKMwRvMMpXJtkiCuWIoAcKBE/GXmdz3QlY3wjmvEGQCz1VmNVkHut63/1s8leYikc+BaOBaCitdOSMShRCGh5OK3AgfdIdjg/OGeYTBeD7nrlkLv3bMKhLWMNUtVPHzvY/dWJJW34thCCeeV8Pt6dpBjZZRqnYdRCvHcVCc5fkLxmRFc2oF2uUDOM4JnUn/cuLBETaw85FoXgSVoH1bn71CY4CM6WXBSMQU0Qzvb8mFc1KoMnraw+6lt5LvRkN48SATkbhrrUKZ6bl1+HvJdQZbJA2gX7RJJG6dLUa4t/XIEteLDVtC6ipfALIJd3i3e/mBtUV4UubIdoIYMMA=
    - secure: OMUsOpLIWCPcNkVdHUKFF13ukt1cFLXPFBwktM3anr2BGqs4tyfPw9e9EZiOv3BKF2s859PE+kCiF1fyrxDyuQcJUIJaKyFNkzK9LFshcl/cz9usQQbrjxU+Y+urVrWz71r6zBapNFbfDgkGbME/wa6nPutynXYGon4HagF/hcIFTJnpTUwN8dpXWxrxbBSVNEpT33jJaFm6e7iwXoq6Uti3OzWotfY6fXa3C9rc0um7CUTQ7pmNzOox2eFTVTw/kY02+a25lAB1x8bZkaV6nZfA79vFwKg1RvOaTaOSjx9g5hn0Qcnkt242yuLpO813e1988OIXGSMWWwNWCLh0dgKNiLWvrF+ClBZ8YSbyS6TMNuqUKXH8s/XX4asf+NZKjbzLZl7VA2dskBMEbTXxQJdl7lENSdOb61bA43uoOOsDQ4WnHm39hU2GdypJzNkmN59kW7URSbTo5g2BQebGtEJRE1BnrAQ0tjc665J2jiqcuOE5lcv+UscF7gsIXQOjVZ+Yl2gLlsAik6bgoVn0U1ZHO4IPzXNHtRhJagb1oPpGfKjMHIHt6Bk48COxtjAZNtla0I1Y5T6Hp9wdI+MUgfMoOI7PPNJjoY72xDxhPwD+IKJ6i/wSn43iqiR9e2PPaHuw25SYwdmqIkVIqI7JqtygxWdOKRaSIbfqqGMkdcg=
